# Generated by Django 5.2 on 2025-05-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_remove_movie_poster_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Drama', 'Drama')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
