# Generated by Django 5.2 on 2025-05-20 10:00

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_movie_poster_alter_movie_genre_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comeduy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Western', 'Western'), ('Other', 'Other'), ('None', 'None')], default=['None'], max_length=141),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comeduy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Western', 'Western'), ('Other', 'Other'), ('None', 'None')], max_length=50),
        ),
    ]
