# Generated by Django 5.2 on 2025-05-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_movie_genres_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
