# Generated by Django 5.2 on 2025-05-20 10:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_remove_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Western', 'Western'), ('Other', 'Other'), ('None', 'None')], default=['None'], max_length=141),
        ),
    ]
