# Generated by Django 5.2 on 2025-05-20 15:18

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_alter_movie_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Superhero', 'Superhero'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Western', 'Western'), ('Other', 'Other')], default=['Other'], max_length=147),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watch_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
