# Generated by Django 5.2 on 2025-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_movie_video_url_movie_views_count_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default4.png', null=True, upload_to='profile_pics/'),
        ),
    ]
