# Generated by Django 5.2 on 2025-05-21 04:59

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-watch_date']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='views_count',
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Superhero', 'Superhero'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Other', 'Other')], default=['Other'], max_length=139),
        ),
    ]
