# Generated by Django 5.2 on 2025-06-06 09:15

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_alter_userinteraction_options_remove_movie_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romantic', 'Romantic'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Superhero', 'Superhero'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Family', 'Family'), ('Other', 'Other')], default=['Other'], max_length=146),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default3.png', null=True, upload_to='profile_pics/'),
        ),
    ]
